name: Autoupdate pre-commit hooks
on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v8.1.0
      - run: uvx prek auto-update
      - uses: peter-evans/create-pull-request@v8
        with:
          title: "chore: autoupdate pre-commit hooks"
          commit-message: "chore: autoupdate pre-commit hooks"
          branch: chore/autoupdate-hooks
          delete-branch: true
